name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:      
    
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg_root: [./Packages/RosettaUI, ./Packages/RosettaUI.UIToolkit]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'

    - run: npm publish
      working-directory: ${{ matrix.pkg_root }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
